name: my_protfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.11.0
  get: ^3.24.0
  firebase_core: ^0.6.0
  cloud_firestore: ^0.15.0
  profanity_filter: ^1.0.4
  fluttertoast: ^7.1.6
  scroll_to_index: ^1.0.6
  flutter_chat_bubble: ^1.0.2
  email_validator: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/owner/1.jpg
    - assets/unknown/upcomming.jpg
    - assets/projects/easytmdb/1.png
    - assets/projects/tolet/1.jpg
    - assets/projects/tolet/2.jpg
    - assets/projects/tolet/3.jpg
    - assets/projects/tolet/4.jpg
    - assets/projects/tolet/5.jpg
    - assets/projects/tolet/6.jpg
    - assets/projects/diuDonate/1.jpg
    - assets/projects/diuDonate/2.jpg
    - assets/projects/diuDonate/3.jpg
    - assets/projects/comboFighter/1.png
    - assets/projects/comboFighter/2.png
    - assets/projects/comboFighter/3.png
    - assets/projects/comboFighter/4.png
    - assets/projects/guessNumber/1.jpg
    - assets/projects/guessNumber/2.jpg
    - assets/projects/guessNumber/3.jpg
    - assets/projects/guessNumber/4.jpg
    - assets/projects/guessNumber/5.jpg
    - assets/projects/quiz/1.png
    - assets/projects/quiz/2.png
    - assets/projects/quiz/3.png
    - assets/projects/quiz/4.png
    - assets/projects/quiz/5.png
    - assets/projects/diuProjectStore/1.png
    - assets/projects/17dof/1.jpg
    - assets/projects/17dof/2.jpg
    - assets/projects/opengl/1.png
    - assets/projects/prosiddho/1.jpg
    - assets/projects/prosiddho/2.jpg
    - assets/projects/prosiddho/3.jpg
    - assets/projects/prosiddho/4.jpg
    - assets/projects/prosiddho/5.jpg
    - assets/projects/prosiddho/6.jpg
    - assets/projects/prosiddho/7.jpg
    - assets/projects/prosiddho/8.jpg
    - assets/projects/prosiddho/9.jpg
    - assets/projects/prosiddho/10.jpg
    - assets/projects/prosiddho/11.jpg
    - assets/projects/prosiddho/12.jpg
    - assets/projects/prosiddho/13.jpg
    - assets/projects/prosiddho/14.jpg
    - assets/projects/prosiddho/15.jpg
    - assets/projects/prosiddho/16.jpg
    - assets/projects/prosiddho/17.jpg
    - assets/projects/prosiddho/18.jpg
    - assets/projects/prosiddho/19.jpg
    - assets/projects/dictionary/1.png
    - assets/projects/dictionary/2.png
    - assets/projects/dictionary/3.png
    - assets/projects/guessNumber2/1.jpg
    - assets/projects/guessNumber2/2.jpg
    - assets/projects/guessNumber2/3.jpg
    - assets/projects/guessNumber2/4.jpg
    - assets/projects/guessNumber2/5.jpg
    - assets/projects/guessNumber2/6.jpg
    - assets/projects/guessNumber2/7.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
